apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-go
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-go-img
  template:
    metadata:
      labels:
        app: hello-go-img
    spec:
      containers:
      - name: image-api
        image: siyangzhang/hello-go-img
        imagePullPolicy: Never
        resources:
          limits:
            memory: "64Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
